### ISSUE TITLE
仓库数量与mp价格带不出

### ISSUE THREAD

**Issue by ElvisZeng** [ShenHaiSu/SimComp-Tools#9]
在仓库的市价卖出界面中，点击全部，库存数量无法带入到输入框
![image](https://github.com/user-attachments/assets/7b103aed-16dd-4ab6-8981-af832704738c)
同样，金额也无法带出
![image](https://github.com/user-attachments/assets/3ba7d5ee-9fd0-49e0-a7f5-49b6121c8be4)
最后，建议在金额处添加一个mp-n*最小单位价格

**Comment by ShenHaiSu** [comment]
观察到游戏界面似乎不是简体中文语言，不进行bug复现测试，不受理。

**Comment by ShenHaiSu** [comment]
请切换到简体中文后进一步测试如果依然复现bug，请再次提交新议题。

**Comment by ElvisZeng** [comment]
切换到简体中文后正常显示，谢谢
